import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'AI Standards & Ethics Policy | Flâneur',
  description: 'Our commitment to AI transparency, editorial integrity, and compliance with global standards including the EU AI Act and C2PA.',
};

export default function StandardsPage() {
  return (
    <div className="min-h-screen bg-canvas">
      <div className="max-w-3xl mx-auto px-4 py-16">
        {/* Back link */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-xs tracking-widest uppercase text-neutral-400 hover:text-white mb-12"
        >
          <span>&larr;</span>
          <span>Back to Home</span>
        </Link>

        <article className="prose prose-neutral prose-invert max-w-none">
          <h1 className="text-4xl font-light text-neutral-100 mb-2">
            AI Standards & Ethics Policy
          </h1>

          <section className="mt-12">
            <h2 className="text-2xl font-semibold text-neutral-200 mb-4">
              Our Commitment to Truth & Transparency
            </h2>
            <p className="text-neutral-300 leading-relaxed text-lg">
              We believe that AI can deliver speed without sacrificing integrity. To ensure clarity
              for our readers and compliance with global standards (including C2PA), we adhere to
              the following strict editorial protocols.
            </p>
          </section>

          <section className="mt-12">
            <h3 className="text-xl font-semibold text-neutral-200 mb-4">
              1. Text & Reporting Transparency
            </h3>
            <p className="text-neutral-300 leading-relaxed mb-4">
              We distinguish between human reporting and AI synthesis.
            </p>
            <ul className="space-y-4 text-neutral-300">
              <li>
                <strong className="text-neutral-100">The "Synthesized Brief" Tag:</strong>{' '}
                Every story generated by our system is explicitly marked with a visible{' '}
                <span className="inline-block bg-neutral-800 text-neutral-400 text-sm px-2 py-0.5 rounded">
                  AI-Synthesized Brief
                </span>{' '}
                tag at the top of the content.
              </li>
              <li>
                <strong className="text-neutral-100">Sourcing Protocol:</strong>{' '}
                We do not obscure our sources. Every brief includes a direct attribution footer,
                hyperlinking to the primary reporting from verified outlets (e.g., <em>Bloomberg,
                The Wall Street Journal</em>) or primary social media signals that informed the synthesis.
              </li>
            </ul>
          </section>

          <section className="mt-12">
            <h3 className="text-xl font-semibold text-neutral-200 mb-4">
              2. Visual Integrity & "Dramatization"
            </h3>
            <p className="text-neutral-300 leading-relaxed mb-4">
              We maintain a strict separation between photojournalism and AI illustration.
              We do not generate photorealistic "fake" news imagery.
            </p>
            <ul className="space-y-4 text-neutral-300">
              <li>
                <strong className="text-neutral-100">Dramatization Disclaimer:</strong>{' '}
                All AI-generated visuals are stylized and clearly labeled with the following disclosure:
                <blockquote className="mt-3 pl-4 border-l-4 border-neutral-600 italic text-neutral-400">
                  <p className="font-semibold not-italic">AI-Generated Illustration | Dramatization</p>
                  <p className="text-sm mt-1">
                    This image is a stylized artistic rendering used for illustrative purposes only.
                    It is not a photograph of the actual event and does not depict real individuals
                    or specific locations.
                  </p>
                </blockquote>
              </li>
              <li>
                <strong className="text-neutral-100">Visual Badging:</strong>{' '}
                A visible{' '}
                <span className="inline-block bg-black/70 text-white text-xs px-2 py-1 rounded">
                  AI Illustration
                </span>{' '}
                badge is permanently overlaid on the image asset itself, ensuring transparency
                even if the image is shared off-platform.
              </li>
            </ul>
          </section>

          <section className="mt-12">
            <h3 className="text-xl font-semibold text-neutral-200 mb-4">
              3. Technical Provenance (C2PA)
            </h3>
            <p className="text-neutral-300 leading-relaxed mb-4">
              We believe in cryptographic truth. Our verification extends beyond what the human eye can see.
            </p>
            <ul className="space-y-4 text-neutral-300">
              <li>
                <strong className="text-neutral-100">Content Credentials:</strong>{' '}
                We inject <strong>C2PA (Coalition for Content Provenance and Authenticity)</strong> metadata
                into the file header of every generated image.
              </li>
              <li>
                <strong className="text-neutral-100">The "Digital Fingerprint":</strong>{' '}
                This cryptographic signature (<code className="bg-neutral-800 px-1.5 py-0.5 rounded text-sm">c2pa.created_by_ai</code>)
                allows browsers, news aggregators (like Google News), and operating systems to independently
                verify that our content is AI-generated and authentically published by us, preventing
                deepfake manipulation.
              </li>
            </ul>
          </section>

          <section className="mt-16 pt-8 border-t border-white/[0.08]">
            <p className="text-sm text-neutral-500">
              This policy is effective as of February 2026 and is updated regularly to comply with
              evolving regulations including the EU AI Act and platform requirements from Apple and Google.
            </p>
            <p className="text-sm text-neutral-500 mt-2">
              Questions about our AI practices? Contact us at{' '}
              <a href="mailto:ethics@readflaneur.com" className="text-blue-600 hover:underline">
                ethics@readflaneur.com
              </a>
            </p>
          </section>
        </article>
      </div>
    </div>
  );
}
