import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'AI Standards & Ethics Policy | Flâneur',
  description: 'Our commitment to AI transparency, editorial integrity, and compliance with global standards including the EU AI Act and C2PA.',
};

export default function StandardsPage() {
  return (
    <div className="py-12 px-4">
      <div className="mx-auto max-w-2xl">
        <h1 className="text-2xl font-light tracking-wide mb-8">
          AI Standards & Ethics Policy
        </h1>

        <p className="text-neutral-400 mb-8">
          We believe that AI can deliver speed without sacrificing integrity. To ensure clarity
          for our readers and compliance with global standards (including C2PA), we adhere to
          the following strict editorial protocols.
        </p>

        <div className="space-y-8">
          <section>
            <h2 className="text-lg font-medium mb-3">Text & Reporting Transparency</h2>
            <p className="text-sm text-neutral-400 mb-3">
              We distinguish between human reporting and AI synthesis.
            </p>
            <ul className="space-y-3 text-sm text-neutral-400">
              <li>
                <strong className="text-neutral-200">The "Synthesized Brief" Tag:</strong>{' '}
                Every story generated by our system is explicitly marked with a visible
                AI-Synthesized Brief tag at the top of the content.
              </li>
              <li>
                <strong className="text-neutral-200">Sourcing Protocol:</strong>{' '}
                We do not obscure our sources. Every brief includes a direct attribution footer,
                hyperlinking to the primary reporting from verified outlets or primary social media
                signals that informed the synthesis.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-medium mb-3">Visual Integrity & Dramatization</h2>
            <p className="text-sm text-neutral-400 mb-3">
              We maintain a strict separation between photojournalism and AI illustration.
              We do not generate photorealistic "fake" news imagery.
            </p>
            <ul className="space-y-3 text-sm text-neutral-400">
              <li>
                <strong className="text-neutral-200">Dramatization Disclaimer:</strong>{' '}
                All AI-generated visuals are stylized and clearly labeled with a disclosure
                stating the image is a stylized artistic rendering used for illustrative purposes
                only, not a photograph of the actual event.
              </li>
              <li>
                <strong className="text-neutral-200">Visual Badging:</strong>{' '}
                A visible AI Illustration badge is permanently overlaid on the image asset itself,
                ensuring transparency even if the image is shared off-platform.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-medium mb-3">Technical Provenance (C2PA)</h2>
            <p className="text-sm text-neutral-400 mb-3">
              We believe in cryptographic truth. Our verification extends beyond what the human eye can see.
            </p>
            <ul className="space-y-3 text-sm text-neutral-400">
              <li>
                <strong className="text-neutral-200">Content Credentials:</strong>{' '}
                We inject C2PA (Coalition for Content Provenance and Authenticity) metadata
                into the file header of every generated image.
              </li>
              <li>
                <strong className="text-neutral-200">The Digital Fingerprint:</strong>{' '}
                This cryptographic signature allows browsers, news aggregators, and operating systems
                to independently verify that our content is AI-generated and authentically published
                by us, preventing deepfake manipulation.
              </li>
            </ul>
          </section>

          <section className="pt-8 border-t border-white/[0.08]">
            <p className="text-sm text-neutral-500">
              This policy is effective as of February 2026 and is updated regularly to comply with
              evolving regulations including the EU AI Act and platform requirements from Apple and Google.
            </p>
            <p className="text-sm text-neutral-500 mt-2">
              Questions about our AI practices? Contact us at{' '}
              <a href="mailto:ethics@readflaneur.com" className="text-neutral-100 underline decoration-neutral-600 hover:text-white">
                ethics@readflaneur.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
