-- Audio bulletin scripts table for yous.news syndication
-- Stores hourly bulletin scripts with phonetic pronunciations
-- Generated by Flaneur at :55, polled by yous.news at :00

CREATE TABLE IF NOT EXISTS audio_bulletin_scripts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  bulletin_date DATE NOT NULL,
  hour TEXT NOT NULL CHECK (hour ~ '^\d{2}$'),
  script TEXT NOT NULL,
  pronunciations JSONB NOT NULL DEFAULT '{}',
  story_count INTEGER NOT NULL DEFAULT 5,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(bulletin_date, hour)
);

-- Index for the GET endpoint lookup
CREATE INDEX idx_audio_bulletin_date_hour ON audio_bulletin_scripts(bulletin_date, hour);

-- RLS: service_role only (cron writes, syndication API reads via service role)
ALTER TABLE audio_bulletin_scripts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access"
  ON audio_bulletin_scripts
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Auto-cleanup: keep 7 days of bulletins
-- (can be extended if we want historical analysis)
COMMENT ON TABLE audio_bulletin_scripts IS 'Hourly news bulletin scripts for yous.news TTS. Generated at :55 by Flaneur, polled at :00 by yous.news.';
